# Jupter Basics

In [1]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"#show intermediate output

- NumPy arrays contain values of a single type
- A Python integer is a pointer to a position in memory containing all the Python object information, including the bytes that contain the integer value. This extra information in the Python integer structure is what allows Python to be coded so **freely and dynamically**. All this additional information in Python types comes at a **cost**, however, which becomes especially apparent in structures that combine many of these objects.

# Learning notes from 02.00-Introduction-to-NumPy of  [Python Data Science Handbook](http://shop.oreilly.com/product/0636920034919.do)

## examples for basic operations

In [2]:
import numpy as np

np.random.seed(1)  # seed for reproducibility
x1=np.random.randint(10, size=6)  # One-dimensional array

np.array([range(i, i + 3) for i in [2, 4, 6]])


#NumPy arrays have a fixed type
x1.dtype
x1[0] = 3.14159  # this will be truncated!
x1

#x[start:stop:step]
#when the step value is negative,the defaults for start and stop are swapped
x1[::-1]  # all elements, reversed
x1[2::-2]  # reversed every other from index 2

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

dtype('int32')

array([3, 8, 9, 5, 0, 0])

array([0, 0, 5, 9, 8, 3])

array([9, 3])

In [42]:
x2=np.random.randint(10, size=(3,3))
x2

b = x2[:2, :2]
b
b[0, 0] = 199
x2
#This default behavior is actually quite useful: it means that when we work with large datasets, 
#we can access and process pieces of these datasets without the need to copy the underlying data buffer.
#isn't this feature easily leading to mistakes???

x2_sub_copy = x2[:2, :2].copy()
x2_sub_copy[0, 0] = 42
x2

array([[6, 8, 0],
       [2, 7, 7],
       [9, 7, 3]])

array([[6, 8],
       [2, 7]])

array([[199,   8,   0],
       [  2,   7,   7],
       [  9,   7,   3]])

array([[199,   8,   0],
       [  2,   7,   7],
       [  9,   7,   3]])

In [47]:
x = np.arange(5)

y = np.zeros(10)
np.power(2, x, out=y[::2])
#this is more efficient than:
y

y1 = np.zeros(10)
y1[::2] = 2 ** x
y1

array([ 1.,  2.,  4.,  8., 16.])

array([ 1.,  0.,  2.,  0.,  4.,  0.,  8.,  0., 16.,  0.])

array([ 1.,  0.,  2.,  0.,  4.,  0.,  8.,  0., 16.,  0.])

In [ ]:
np.multiply.reduce(x)#calling reduce on the multiply ufunc results in the product of all array elements


| Operator	    | Equivalent ufunc    | Description                           |
|---------------|---------------------|---------------------------------------|
|``+``          |``np.add``           |Addition (e.g., ``1 + 1 = 2``)         |
|``-``          |``np.subtract``      |Subtraction (e.g., ``3 - 2 = 1``)      |
|``-``          |``np.negative``      |Unary negation (e.g., ``-2``)          |
|``*``          |``np.multiply``      |Multiplication (e.g., ``2 * 3 = 6``)   |
|``/``          |``np.divide``        |Division (e.g., ``3 / 2 = 1.5``)       |
|``//``         |``np.floor_divide``  |Floor division (e.g., ``3 // 2 = 1``)  |
|``**``         |``np.power``         |Exponentiation (e.g., ``2 ** 3 = 8``)  |
|``%``          |``np.mod``           |Modulus/remainder (e.g., ``9 % 4 = 1``)|


For **efficiency** reasons, whenever possible, make sure that you are using the NumPy version of these aggregates when operating on NumPy arrays, instead of the built-in functions!

In [48]:
big_array = np.random.rand(1000000)
%timeit min(big_array)
%timeit np.min(big_array)

55.1 ms ± 485 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
352 µs ± 6.91 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [54]:
a = np.arange(3).reshape((3, 1))
b = np.arange(3)
a
b
a-b

a[:, np.newaxis].shape

array([[0],
       [1],
       [2]])

array([0, 1, 2])

array([[ 0, -1, -2],
       [ 1,  0, -1],
       [ 2,  1,  0]])

(3, 1, 1)

In [58]:
X = np.arange(12).reshape((3, 4))
X
row = np.array([0, 1, 2])
col = np.array([2, 1, 3])

[row[:, np.newaxis], col]

X[row[:, np.newaxis], col]

row[:, np.newaxis] * col

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

[array([[0],
        [1],
        [2]]), array([2, 1, 3])]

array([[ 2,  1,  3],
       [ 6,  5,  7],
       [10,  9, 11]])

array([[0, 0, 0],
       [2, 1, 3],
       [4, 2, 6]])

``and`` and ``or`` perform a single Boolean evaluation on an entire object, while ``&`` and ``|`` perform multiple Boolean evaluations on the content (the individual bits or bytes) of an object.
For Boolean NumPy arrays, the latter is nearly always the desired operation.

In [63]:
rand = np.random.RandomState(42)
X = rand.rand(10, 2)
X
dist_sq = np.sum((X[:, np.newaxis, :] - X[np.newaxis, :, :]) ** 2, axis=-1)# compute the matrix of square distances 
dist_sq.shape

# for each pair of points, compute differences in their coordinates
differences = X[:, np.newaxis, :] - X[np.newaxis, :, :]
X[:, np.newaxis, :].shape
X[np.newaxis, :, :].shape

array([[0.37454012, 0.95071431],
       [0.73199394, 0.59865848],
       [0.15601864, 0.15599452],
       [0.05808361, 0.86617615],
       [0.60111501, 0.70807258],
       [0.02058449, 0.96990985],
       [0.83244264, 0.21233911],
       [0.18182497, 0.18340451],
       [0.30424224, 0.52475643],
       [0.43194502, 0.29122914]])

(10, 10)

(10, 1, 2)

(1, 10, 2)

## data type

| Data type	    | Description |
|---------------|-------------|
| ``bool_``     | Boolean (True or False) stored as a byte |
| ``int_``      | Default integer type (same as C ``long``; normally either ``int64`` or ``int32``)| 
| ``intc``      | Identical to C ``int`` (normally ``int32`` or ``int64``)| 
| ``intp``      | Integer used for indexing (same as C ``ssize_t``; normally either ``int32`` or ``int64``)| 
| ``int8``      | Byte (-128 to 127)| 
| ``int16``     | Integer (-32768 to 32767)|
| ``int32``     | Integer (-2147483648 to 2147483647)|
| ``int64``     | Integer (-9223372036854775808 to 9223372036854775807)| 
| ``uint8``     | Unsigned integer (0 to 255)| 
| ``uint16``    | Unsigned integer (0 to 65535)| 
| ``uint32``    | Unsigned integer (0 to 4294967295)| 
| ``uint64``    | Unsigned integer (0 to 18446744073709551615)| 
| ``float_``    | Shorthand for ``float64``.| 
| ``float16``   | Half precision float: sign bit, 5 bits exponent, 10 bits mantissa| 
| ``float32``   | Single precision float: sign bit, 8 bits exponent, 23 bits mantissa| 
| ``float64``   | Double precision float: sign bit, 11 bits exponent, 52 bits mantissa| 
| ``complex_``  | Shorthand for ``complex128``.| 
| ``complex64`` | Complex number, represented by two 32-bit floats| 
| ``complex128``| Complex number, represented by two 64-bit floats| 

In [20]:
np.iinfo(np.uint16).max
np.finfo(np.float16).max
np.finfo(np.float16).min
np.finfo(np.float16).eps#the smallest number > 0 representable
np.finfo(np.float16).resolution#the approximate decimal number resolution

np.finfo(np.float32).eps#the smallest number > 0 representable
np.finfo(np.float32).resolution#the approximate decimal number resolution

65535

65500.0

-65500.0

0.000977

0.001

1.1920929e-07

1e-06

### <font color='red'>Why should I care about data types</font> 

For instance, a pixel value of [Sentinel-2 image](https://developers.google.com/earth-engine/datasets/catalog/COPERNICUS_S2#description) is a. Assuming that you want to keep the value unchanged during the processing, then:

- you cannot convert it to float16
- you can not convert it to float 16 even if it is divided by 10000
- you can convert it to float 32 even if it is divided by 10000

In [20]:
a = np.uint16(65535)
np.float16(65535)

b0=np.uint16(5535)
b=np.float16(b0)
b
c=np.float32(b0)
c

inf

5536.0

5535.0

In [21]:
np.float16(a/10000)
np.float16(65534/10000)

b/10000.0
c/10000.0

np.float32(b/10000.0)
np.float32(c/10000.0)

6.555

6.555

0.5536

0.5535

0.5536

0.5535

In [21]:
np.float32(a/10000)
np.float32(65534/10000)

6.5535

6.5534

# Big-O notation

Big-O notation, in this loose sense, tells you how much time your algorithm will take as you increase the amount of data.
If you have an $\mathcal{O}[N]$ (read "order $N$") algorithm that takes 1 second to operate on a list of length *N*=1,000, then you should expect it to take roughly 5 seconds for a list of length *N*=5,000.
If you have an $\mathcal{O}[N^2]$ (read "order *N* squared") algorithm that takes 1 second for *N*=1000, then you should expect it to take about 25 seconds for *N*=5000.

Notice that the big-O notation by itself tells you nothing about the actual wall-clock time of a computation, but only about its scaling as you change *N*.
Generally, for example, an $\mathcal{O}[N]$ algorithm is considered to have better scaling than an $\mathcal{O}[N^2]$ algorithm, and for good reason. But for small datasets in particular, the algorithm with better scaling might not be faster.
For example, in a given problem an $\mathcal{O}[N^2]$ algorithm might take 0.01 seconds, while a "better" $\mathcal{O}[N]$ algorithm might take 1 second.
Scale up *N* by a factor of 1,000, though, and the $\mathcal{O}[N]$ algorithm will win out.